title: Anders Pollack
baseurl: /portfolio2019 
port: 4001

defaults:
  - scope:
      path: ""
    values:
      layout: default

  - scope:
      path: "/assets/images"
    values:
      image: true

collections:
  project_collections:
    output: true
    permalink: /pojects/:name
