title: Anders Pollack
baseurl: /portfolio2019 
port: 4001
collections_dir: collections
about: "I'm a designer and web developer based in Los Angeles, CA. Get in touch at <a href='mailto:pollack.anders@gmail.com'>pollack.anders@gmail.com</a>"

collections:
  super-deluxe:
    output: true
    name: Super Deluxe
    order: 4
    description: "Graphic design and Shopify development for the Super Deluxe Store; UI design and front-end development for a game show prototype. RIP☠︎"
    permalink: /projects/:name

  website-projects:
    output: true
    name: Website Projects
    order: 3
    description: "Various websites I've made"
    permalink: /projects/:name

  tio:
    output: true
    name: Tuition.io
    order: 2
    description: "UX design and brand collateral for this student loan repayment benefit B2B platform"
    permalink: /projects/:name

  c2st:
    output: true
    name: The Chicago Council on Science and Technology
    order: 1
    description: "Graphic design and web development for a nonprofit organization that promotes science education and outreach"
    permalink: /projects/:name

defaults:
  - scope:
      path: ""
    values:
      layout: default

  - scope:
      path: ""
      type: "super-deluxe"
    values:
      layout: project

  - scope:
      path: ""
      type: "website-projects"
    values:
      layout: project

  - scope:
      path: ""
      type: "tio"
    values:
      layout: project

  - scope:
      path: ""
      type: "c2st"
    values:
      layout: project

  - scope:
      path: "/assets/images"
    values:
      image: true

