domain: anderspollack.com
url: https://www.anderspollack.com
repository: anderspollack/anderspollack.github.io
github: [metadata]
title: Anders Pollack
baseurl: '' 
port: 4001
collections_dir: collections
about: "I'm a designer and web developer based in Los Angeles, CA. Get in touch at <a href='mailto:pollack.anders@gmail.com'>pollack.anders@gmail.com</a>"

collections:
  tools:
    output: true
    name: Software Tools
    order: 6
    description: "Software Tools I've made or configured for my day-to-day use"
    permalink: /projects/:name
  
  new-media:
    output: true
    name: New Media Projects
    order: 5
    description: "Interactive and multimedia works"
    permalink: /projects/:name

  super-deluxe:
    output: true
    name: Super Deluxe
    order: 4
    description: "Graphic design and Shopify development for the Super Deluxe Store; UI design and front-end development for a game show prototype. RIP☠︎"
    permalink: /projects/:name

  website-projects:
    output: true
    name: Website Projects
    order: 3
    description: "Various websites I've made"
    permalink: /projects/:name

  tio:
    output: true
    name: Tuition.io
    order: 2
    description: "UX design and brand collateral for this student loan repayment benefit B2B platform"
    permalink: /projects/:name

  c2st:
    output: true
    name: The Chicago Council on Science and Technology
    order: 1
    description: "Graphic design and web development for a nonprofit organization that promotes science education and outreach"
    permalink: /projects/:name

defaults:
  - scope:
      path: ""
    values:
      layout: default

  - scope:
      path: ""
      type: "tools"
    values:
      layout: project

  - scope:
      path: ""
      type: "new-media"
    values:
      layout: project

  - scope:
      path: ""
      type: "super-deluxe"
    values:
      layout: project

  - scope:
      path: ""
      type: "website-projects"
    values:
      layout: project

  - scope:
      path: ""
      type: "tio"
    values:
      layout: project

  - scope:
      path: ""
      type: "c2st"
    values:
      layout: project

  - scope:
      path: "/assets/images"
    values:
      image: true
